apiVersion: v2
appVersion: 0.1.73
description: A Base Helm chart for Kubernetes - Added support for volumes/volumeMounts format
icon: https://media.licdn.com/dms/image/C4E0BAQEdK6tkXfbtXQ/company-logo_200_200/0/1674118[…]47483647&v=beta&t=66-Xh3XKEy8l4jC5BCzb-73JqBDxRZPWACNt9KRiL4M
name: base
type: application
version: 0.1.73
